name: Build

on: 
  push:
    tags:
      - "v*" #push events to matfching v* i.e. v1.0, v20.15.10

env:
  BUILD_TYPE: Release
  BUILD_PATH: build
  DEVEL_PATH: devel
  INSTALL_PATH: install
  DEB_PATH: package

jobs:
  catkin_build:
    strategy:
      matrix:
        container: ["melodic", "kinetic"]
    runs-on: ubuntu-20.04
    container: ros:${{ matrix.container }}

    steps:
    - name: update git
      run: |
        apt-get update 
        apt-get install -y software-properties-common
        add-apt-repository ppa:git-core/ppa
        apt-get update
        apt-get install -y git
    - uses: actions/checkout@v2
      with:
        path: src/darknet_ros 
        submodules: 'recursive'

    - name: rosdep install
      run: |
        apt-get update
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
    - name: catkin_make
      shell: bash
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        catkin_make -DCMAKE_BUILD_TYPE=$BUILD_TYPE install
    - name: catkin_make run_tests
      shell: bash
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        catkin_make run_tests
        catkin_test_results
    - name: make deb bag
      shell: bash
      run: |
        VERSION='1.0'
        DATE=`date +%y%m%d`
        HASH_KEY=`git rev-parse --verify --short HEAD`
        cat >${DEB_PATH}/DEBIAN/control << EOF 
        Package: ros-${ROS_DISTRO}-ros-node
        Version: ${VERSION}-${DATE}-${HASH_KEY}
        Section: misc
        Priority: optional
        Architecture: amd64
        Maintainer: 851045076@qq.com
        Description: The ros_node package
        EOF

        cp -r install/bin ${DEB_PATH}/opt/ros/${ROS_DISTRO}/
        cp -r install/include ${DEB_PATH}/opt/ros/${ROS_DISTRO}/
        cp -r install/lib ${DEB_PATH}/opt/ros/${ROS_DISTRO}/
        cp -r install/share ${DEB_PATH}/opt/ros/${ROS_DISTRO}/

        dpkg-deb --build ${DEB_PATH}/ ros-${ROS_DISTRO}-ros-node-${DATE}-${HASH_KEY}.deb

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
#          tag_name: ${{ github.ref }}
#          name: Release ${{ github.ref }}
        # body_path: %{{ }}/  CHANGELOG.txt
        draft: false
        prerelease: false
        files: |
          *.deb