name: publilsh release

on: 
  push:
    tags:
      - "v*" #push events to matfching v* i.e. v1.0, v20.15.10

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: main}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
          - {ROS_DISTRO: kinetic, ROS_REPO: main}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - name: zip
        run: |
          tar -cvf build.tar.gz ./build/
          tar -cvf devel.tar.gz ./devel/

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
#          tag_name: ${{ github.ref }}
#          name: Release ${{ github.ref }}
          body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            build.tar.gz
            devel.tar.gz
            LICENSE 